# Generated by Django 6.0.3 on 2026-03-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('autore', models.CharField(max_length=100)),
                ('anno', models.IntegerField()),
            ],
        ),
    ]
