# Generated by Django 6.0.3 on 2026-03-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='genere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
