# Generated by Django 6.0.3 on 2026-03-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_libro_genere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cognome', models.CharField(max_length=200)),
                ('nazionalita', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='pagine',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
