# Generated by Django 6.0.3 on 2026-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_autore_libro_pagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='lingua_og',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
