# Generated by Django 6.0.3 on 2026-03-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_libro_lingua_og'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autore',
        ),
    ]
