# Generated by Django 6.0.3 on 2026-03-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_autore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lingua_og',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lingua_og', models.CharField(max_length=50)),
            ],
        ),
    ]
