# Generated by Django 6.0.3 on 2026-03-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_lingua_og'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='anno',
            field=models.PositiveIntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='libro',
            name='pagine',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
