# Generated by Django 6.0.3 on 2026-03-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_alter_libro_anno_alter_libro_pagine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='anno',
        ),
    ]
