# Generated by Django 6.0.3 on 2026-03-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_remove_libro_anno'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='anno',
            field=models.PositiveIntegerField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
