# Generated by Django 6.0.3 on 2026-03-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_libro_anno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='anno',
            field=models.PositiveIntegerField(),
        ),
    ]
