# Generated by Django 6.0.3 on 2026-03-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_alter_libro_anno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='pagine',
        ),
    ]
